[2024-12-31T02:24:14.198+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-31T02:24:14.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.untar_dataset manual__2024-12-31T02:24:06.780389+00:00 [queued]>
[2024-12-31T02:24:14.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.untar_dataset manual__2024-12-31T02:24:06.780389+00:00 [queued]>
[2024-12-31T02:24:14.275+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-31T02:24:14.315+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): untar_dataset> on 2024-12-31 02:24:06.780389+00:00
[2024-12-31T02:24:14.342+0000] {standard_task_runner.py:63} INFO - Started process 609 to run task
[2024-12-31T02:24:14.355+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'untar_dataset', 'manual__2024-12-31T02:24:06.780389+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpvld0er27']
[2024-12-31T02:24:14.359+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask untar_dataset
[2024-12-31T02:24:14.389+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-31T02:24:14.482+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_toll_data.untar_dataset manual__2024-12-31T02:24:06.780389+00:00 [running]> on host 31e8d76a82c8
[2024-12-31T02:24:14.627+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vim@gmail.com' AIRFLOW_CTX_DAG_OWNER='Vimalesh' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='untar_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T02:24:06.780389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-31T02:24:06.780389+00:00'
[2024-12-31T02:24:14.630+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-31T02:24:14.651+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-31T02:24:14.652+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-31T02:24:14.668+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data, task_id=untar_dataset, run_id=manual__2024-12-31T02:24:06.780389+00:00, execution_date=20241231T022406, start_date=20241231T022414, end_date=20241231T022414
[2024-12-31T02:24:14.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-31T02:24:14.738+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-12-31T02:24:14.740+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
